services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: quickbite-runner
    restart: unless-stopped

    volumes:
      - ./runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock